language: php

php:
  - '7.0'

services:
  - mysql

before_install:
  - sudo apt-get -qq update
  - sudo pear install Net_LDAP2
  - mysql -e "create database IF NOT EXISTS hrm_ng;" -uroot

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install

script: phpunit --configuration phpunit.xml



