language: php

php:
  - '7.0'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y php7.0-ldap php7.0-mysql php7.0-pgsql

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

script: phpunit --configuration phpunit.xml



